### ISSUE TITLE
Render_value=True

### ISSUE THREAD

**Issue by cicognani1971** [hmeza/django_password_eye#1]
Hello,
I would like to know how can I implement in Django_Password_Eye the render_value=True parameter that I can use with widget=forms.PasswordInput(render_value=True),
Regards
Vittorio Cicognani

**Comment by hmeza** [comment]
Hi,

Thanks for reporting. It has been fixed in version 1.0.8.
In case you're interested in how it was implemented, please check the merged pull request you can see above this comment.

Best
